export const DashboardPageId = 'dashboard'
export const UserProfilePageId = 'profile'
export const UserSquadsPageId = 'squads'
export const SingleSquadPageId = 'singleSquad'

export const LogPageId = 'logs'
export const ValorantLogPageId = 'valorantLogs'
export const ValorantMatchPageId = 'valorantMatch'
export const AimlabLogPageId = 'aimlabLogs'
export const AimlabMatchPageId = 'aimlabMatch'
export const HearthstoneLogPageId = 'hearthstoneLogs'
export const HearthstoneConstructedLogPageId = 'hearthstoneConstructedLogs'
export const HearthstoneArenaLogPageId = 'hearthstoneArenaLogs'
export const HearthstoneArenaRunMatchLogPageId = 'HearthstoneArenaRunMatchLog'
export const HearthstoneBrawlLogPageId = 'hearthstoneBrawlLogs'
export const HearthstoneBattlegroundsLogPageId = 'hearthstoneBattlegroundsLogs'
export const HearthstoneDuelLogPageId = 'hearthstoneDuelLogs'
export const HearthstoneDuelRunMatchLogPageId = 'hearthstoneDuelRunMatchLog'
export const HearthstoneMatchPageId = 'hearthstoneMatch'
export const WowLogPageId = 'wowLogs'
export const WowEncounterLogPageId = 'wowEncounters'
export const WowChallengeLogPageId = 'wowChallenges'
export const WowMatchPageId = 'wowMatch'

export const PerformancePageId = 'performance'
export const VizStatsPageId = 'visualization'