export const DashboardPageId = 'dashboard'
export const UserProfileSlugPageId = 'profileSlug'
export const UserProfileIdPageId = 'profileId'
export const UserSquadsPageId = 'squads'
export const SingleSquadPageId = 'singleSquad'

export const LogPageId = 'logs'
export const ValorantLogPageId = 'valorantLogs'
export const ValorantMatchPageId = 'valorantMatch'
export const AimlabLogPageId = 'aimlabLogs'
export const AimlabMatchPageId = 'aimlabMatch'
export const HearthstoneLogPageId = 'hearthstoneLogs'
export const HearthstoneConstructedLogPageId = 'hearthstoneConstructedLogs'
export const HearthstoneArenaLogPageId = 'hearthstoneArenaLogs'
export const HearthstoneArenaRunMatchLogPageId = 'HearthstoneArenaRunMatchLog'
export const HearthstoneBrawlLogPageId = 'hearthstoneBrawlLogs'
export const HearthstoneBattlegroundsLogPageId = 'hearthstoneBattlegroundsLogs'
export const HearthstoneDuelLogPageId = 'hearthstoneDuelLogs'
export const HearthstoneDuelRunMatchLogPageId = 'hearthstoneDuelRunMatchLog'
export const HearthstoneMatchPageId = 'hearthstoneMatch'
export const WowLogPageId = 'wowLogs'
export const WowEncounterLogPageId = 'wowEncounters'
export const WowChallengeLogPageId = 'wowChallenges'
export const WowArenaLogPageId = 'wowArenas'
export const WowInstanceLogPageId = 'wowInstances'
export const WowMatchPageId = 'wowMatch'
export const TftLogPageId = 'tftLogs'
export const TftMatchPageId = 'tftMatch'
export const LolLogPageId = 'lolLogs'
export const LolMatchPageId = 'lolMatch'
export const CsgoLogPageId = 'csgoLogs'
export const CsgoMatchPageId = 'csgoMatch'

export const PerformancePageId = 'performance'
export const VizStatsPageId = 'visualization'

export const LoginPageId = 'login'
export const RegisterPageId = 'register'
export const ForgotPasswordPageId = 'forgotPw'
export const VerifyEmailPageId = 'verifyEmail'

export const DiscordOauthPageId = 'discordOauth'
export const TwitchOauthPageId = 'twitchOauth'
export const RsoOauthPageId = 'rso'
export const InviteResponsePageId = 'inviteResponse'
export const LinkResponsePageId = 'linkResponse'
export const ShareRedirectPageId = 'share'
export const VideoEditorPageId = 'videoEdit'
export const SettingsPageId = 'settings'

export const ClipLibraryPageId = 'clipLibrary'
export const ClipPageId = 'clip'
export const PlayerPageId = 'player'
export const LocalStoragePageId = 'localStorage'

export const CommunityHomePageId = 'communities'
export const CommunityDiscoverPageId = 'communityDiscover'
export const CommunityPageId = 'communityPage'

export const FavoritesPageId = 'favorites'
export const WatchlistPageId = 'watchlist'
export const PostGameReportPageId = 'postgame'

export const DownloadThanksPageId = 'tydownload'
export const PricingPageId = 'pricing'
export const SubscriptionPageId = 'subscription'