export const DashboardPageId = 'dashboard'

export const LogPageId = 'logs'
export const ValorantLogPageId = 'valorantLogs'
export const ValorantMatchPageId = 'valorantMatch'
export const AimlabLogPageId = 'aimlabLogs'
export const AimlabMatchPageId = 'aimlabMatch'
export const HearthstoneLogPageId = 'hearthstoneLogs'
export const HearthstoneConstructedLogPageId = 'hearthstoneConstructedLogs'
export const HearthstoneArenaLogPageId = 'hearthstoneArenaLogs'
export const HearthstoneArenaRunMatchLogPageId = 'HearthstoneArenaRunMatchLog'
export const HearthstoneBrawlLogPageId = 'hearthstoneBrawlLogs'
export const HearthstoneBattlegroundsLogPageId = 'hearthstoneBattlegroundsLogs'
export const HearthstoneDuelLogPageId = 'hearthstoneDuelLogs'
export const HearthstoneMatchPageId = 'hearthstoneMatch'

export const PerformancePageId = 'performance'
export const VizStatsPageId = 'visualization'